### ISSUE TITLE
Stop showing exported environment variables in deploy script output

### ISSUE THREAD

**Issue by forevermatt** [silinternational/serverless-mfa-api-go#10]
I think we should remove this, so that `export` commands below to cause secrets to be logged.

https://github.com/silinternational/serverless-mfa-api-go/blob/d9aa85f5cd2970f6ebde5da04ad076f610b9dd2f/lambda/deploy.sh#L6-L7

**Comment by devon-sil** [comment]
@briskt @forevermatt Has this been addressed as well?

**Comment by forevermatt** [comment]
> @briskt @forevermatt Has this been addressed as well?

The builds are still outputting those steps, though it [looks like](https://github.com/silinternational/serverless-mfa-api-go/actions/runs/8114997995/job/22181942625#step:3:7) the GitHub Action is redacting the sensitive ones. I don't know how reliable it is to depend on them to hide sensitive values, but for now it's working. 🤷‍♂️ 

We probably could remove that `set -x` line, to avoid this risk, unless @briskt sees a reason not to do that.

**Comment by briskt** [comment]
> > @briskt @forevermatt Has this been addressed as well?
> 
> The builds are still outputting those steps, though it [looks like](https://github.com/silinternational/serverless-mfa-api-go/actions/runs/8114997995/job/22181942625#step:3:7) the GitHub Action is redacting the sensitive ones. I don't know how reliable it is to depend on them to hide sensitive values, but for now it's working. 🤷‍♂️
> 
> We probably could remove that `set -x` line, to avoid this risk, unless @briskt sees a reason not to do that.

The redaction happens, so it seems, because the sensitive data is defined in a GitHub Secret. As for the `set -x` in the script, it is already reversed with a `set +x` before the line that would output the secret.
