### ISSUE TITLE
Lock serverless frame used in deployments to a specific major version

### ISSUE THREAD

**Issue by forevermatt** [silinternational/serverless-mfa-api-go#9]
Currently it doesn't specify, but in the past we've had problems when new major versions come out, so we should probably change this to something like `npm install -g serverless@2`

https://github.com/silinternational/serverless-mfa-api-go/blob/d9aa85f5cd2970f6ebde5da04ad076f610b9dd2f/lambda/deploy.sh#L42

**Comment by Schparky** [comment]
I just worked through the upgrade process on a separate serverless repo. I could probably take care of this one too.

**Comment by devon-sil** [comment]
@briskt or @forevermatt Is this still an issue?

**Comment by forevermatt** [comment]
> @briskt or @forevermatt Is this still an issue?

I'm not sure. It looks like the version is now specified [here](https://github.com/silinternational/serverless-mfa-api-go/blob/639c681456bcd38a73298f8b2c3f4e2c558b61be/Dockerfile#L3), which means we are already specifying the exact version. If I had to guess, I'd say this isn't worth spending more time on for now. My 2 cents.

**Comment by briskt** [comment]
It appears to have been resolved some time ago, but I failed to close this issue.
